### ISSUE TITLE
Addition to Python OOP directory; shorten decorator names?

### ISSUE THREAD

**Issue by metaperl** [Shir0kamii/pyhooks#3]
Hi, your library has been added to [the Python object-oriented programming resources list](https://github.com/metaperl/python-oop/blob/master/README.md#method-munging)

I was wondering if you had ever thought of simpler decorator names like

```
@after('save')
def increment_value(self):
    pass
```

**Comment by Shir0kamii** [comment]
Hi,

Thanks for spreading the word about Pyhooks!

I want to keep descriptive names since I plan on implementing other behaviours, but I think we can add the shorter aliases `after` and `before` for the existing hooks, since I suspect they will be more used anyway.

**Comment by ramnes** [comment]
Any ETA on this @Shir0kamii? :wink:

**Comment by Shir0kamii** [comment]
It's done and released as 1.0.1 on Pypi.
